apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lyzi8zcvs-nodejs 
  janus-idp.io/tekton: lyzi8zcvs-nodejs
  backstage.io/kubernetes-id: lyzi8zcvs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lyzi8zcvs-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml